# Generated by Django 3.0.5 on 2020-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200412_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('skill_level', models.CharField(choices=[('skill-1', '95%'), ('skill-2', '90%'), ('skill-3', '85%'), ('skill-4', '80%'), ('skill-5', '75%'), ('skill-6', '70%')], max_length=30)),
            ],
        ),
    ]
