# Generated by Django 3.0.5 on 2020-04-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=100)),
                ('image_1', models.ImageField(upload_to='portfolio')),
                ('image_2', models.ImageField(upload_to='portfolio')),
                ('image_3', models.ImageField(upload_to='portfolio')),
            ],
        ),
    ]
