#!/bin/bash

# EXPORT LANGUAGES
source /etc/profile.d/lang.sh
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# INSTALL DEPENDENCIES
apt install -y zlib-devel epel-release python3 python3-devel httpd-devel
apt -y groupinstall development
apt update -y
apt install -y mod_ssl

# BUILD MOD_WSGI AND INSTALL
wget "https://github.com/GrahamDumpleton/mod_wsgi/archive/4.5.14.tar.gz"
tar -xzf '4.5.14.tar.gz'
cd ./mod_wsgi-4.5.14
./configure --with-python=/usr/bin/python3.7
make
make install
cd ..
rm -rf mod_wsgi-4.5.14
rm 4.5.14.tar.gz